version: "3.7"

services:
  postgresql:
    image: postgres:15.2
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - './init/init.sh:/docker-entrypoint-initdb.d/init.sh'
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DEV_DATABASES=development_db
      - POSTGRES_DEV_USER=${POSTGRES_DEV_USER}
      - POSTGRES_DEV_PASSWORD=${POSTGRES_DEV_PASSWORD}
    expose:
      - "5435"

volumes:
  postgresql_data:
    driver: local